# fly.toml app configuration file generated for week1-issy-dylan-george-elena-microblogging on 2023-09-20T12:19:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "week1-issy-dylan-george-elena-microblogging"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
